clean:
	$(MAKE) -C 00_assemble clean
	$(MAKE) -C 01_serial_write clean
	$(MAKE) -C 02_serial_write_headers clean
	$(MAKE) -C 03_serial_rw clean
	$(MAKE) -C 04_serial_rw_stack clean
	$(MAKE) -C 05_serial_rw_stack_ld clean
	$(MAKE) -C 06_vector_swi clean
	$(MAKE) -C 07_cstartup clean
